name: variables and secrets

env:
  WF_WAR: "Workflow level variable"

on:
  push:
jobs:
  test_variables:
    env:
      JOB_VAR: "Job level variable"
    name: job to test variables
    runs-on: ubuntu-latest
    steps:
      - name: test variables
        id: stepVar
        env:
          STEP_VAR: "Step level variable"
        run: |
          echo ${{ github.actor }}
          echo $GITHUB_JOB
          echo $WF_WAR
          echo $JOB_WAR
          echo $STEP_WAR
          echo ${{ vars.CONF_VAR }}
          echo ${{ secrets.A_SECRET }}
